# Generated by Django 2.1.2 on 2018-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='artical',
            name='editor_type',
            field=models.CharField(default='base', max_length=20, verbose_name='编辑器类型'),
        ),
        migrations.AlterField(
            model_name='artical',
            name='author',
            field=models.CharField(default='admin', max_length=20, verbose_name='作者'),
        ),
    ]
