# Generated by Django 2.1.2 on 2018-12-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181218_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='editor_type',
        ),
    ]
